"""Specialized OCR VLM provider for document header identification."""
import os
import base64
import re
import httpx
from typing import Dict, Any, Optional, List
from pathlib import Path

from config.logging import logger
from config.settings import get_settings

settings = get_settings()


class OCRVLMProvider:
    """VLM provider for extracting header-level identifiers from onboarding documents."""

    def __init__(self, model: str = "/local-models/numind/NuMarkdown-BB-Thinking",
                 url: str = "http://172.17.58.109:8001/v1/chat/completions"):
        self.model = model
        self.url = url
        self.headers = {"Content-Type": "application/json"}

        # Define the prompt for header-level identification
        self.prompt_header = """The input document is an onboarding document (examples: Aadhaar card, PAN card, Voter ID, Passport, Driving License, Experience Letter, Marksheet, etc.). The goal is to extract unique header-level identifiers to classify the document type.

### STRICT INSTRUCTIONS:
- Extract only unique identifiers such as government seals, department names, organization names, or standard phrases.
- Do not extract personal details like name, address, or ID numbers unless they are part of the unique identifier.
- Do not include line-item or tabular data (e.g., marks in a worksheet).
- Return the output strictly in Markdown format with headers for each field.
- If a unique identifier is found, classify the document type accordingly.

Example Outputs

Aadhaar Card
# Document Type: Aadhaar Card
## Unique Identifier: Government of India
## Issuing Authority: Unique Identification Authority of India (UIDAI)

PAN Card
# Document Type: PAN Card
## Unique Identifier: Income Tax Department
## Issuing Authority: Government of India

Experience Letter
# Document Type: Experience Letter
## Unique Identifier: "This is to certify that."
## Issuing Authority: Employer Organization Name

Marksheet
# Document Type: Marksheet
## Unique Identifier: University of Mumbai
## Issuing Authority: Examination Board

### Logic Flow
- Scan the document for unique textual markers (e.g., "Income Tax Department", "Government of India", "University of Mumbai").
- Match against a predefined dictionary of identifiers + classify document type.
- Extract only the header-level identifiers and issuing authority.
- Return in Markdown format."""

    def encode_image(self, image_path: str) -> str:
        """Encode the image file to base64 string."""
        with open(image_path, "rb") as image_file:
            return base64.b64encode(image_file.read()).decode('utf-8')

    def create_content(self, content_type: str, text: str = None, image_url: str = None) -> List[Dict[str, Any]]:
        """Create content based on content type [img | text]."""
        content = []
        if content_type == 'img':
            content = [
                {"type": "image_url", "image_url": {"url": image_url}}
            ]
        if text:
            content.append({"type": "text", "text": text})
        elif content_type == 'txt':
            content = text

        return content

    def call_api(self, messages: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Call the VLM API."""
        data = {
            "temperature": 0.1,
            "model": self.model,
            "messages": messages
        }

        try:
            response = httpx.post(
                self.url,
                headers=self.headers,
                json=data,
                timeout=120
            )
            response.raise_for_status()
            return response.json()
        except Exception as e:
            logger.error(f"VLM API call failed: {e}")
            raise

    def parse_response(self, content: str) -> str:
        """Extract the text between the 'answer' tags generated by VLM model."""
        match = re.search(r"<answer>\n(.*)\n</answer>", content, re.DOTALL)
        if match:
            return match.group(1)
        return content

    async def analyze_document_header(self, image_path: str) -> str:
        """
        Analyze document header to extract header-level identifiers.

        Args:
            image_path: Path to the document image

        Returns:
            Markdown formatted response with document classification
        """
        try:
            # Check if file exists
            if not os.path.exists(image_path):
                raise FileNotFoundError(f"Image path does not exist: {image_path}")

            # Encode image
            encoded_image = self.encode_image(image_path)
            image_url = f"data:image/jpeg;base64,{encoded_image}"

            # Create conversation messages
            conversation = [
                {
                    "role": "system",
                    "content": (
                        "You are an expert document formatter. Your task is to convert raw document text into clean, structured markdown.\n"
                        "Use headers, bold, tables, and lists as appropriate.\n"
                        "Output only the markdown. Do not add explanations or extra text."
                    )
                },
                {
                    "role": "user",
                    "content": self.create_content(
                        content_type="img",
                        text=self.prompt_header,
                        image_url=image_url
                    )
                }
            ]

            # Call API
            response = self.call_api(conversation)

            # Extract content
            content = response['choices'][0]['message']['content']
            return self.parse_response(content)

        except Exception as e:
            logger.error(f"Document header analysis failed: {e}")
            raise

    def health_check(self) -> bool:
        """Check if the VLM service is available."""
        try:
            response = httpx.get(f"{self.url.replace('/chat/completions', '/models')}", timeout=10)
            return response.status_code == 200
        except Exception as e:
            logger.error(f"VLM health check failed: {e}")
            return False